In [1]:
import torch


In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 52,  79, -72,  -1,  54,  10])

In [3]:
tensor = torch.tensor([[1, 2, 3], [2,2,3.1], [3, 4, 5]])
tensor

tensor([[1.0000, 2.0000, 3.0000],
        [2.0000, 2.0000, 3.1000],
        [3.0000, 4.0000, 5.0000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[-1.3601e-15,  1.1939e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
arange = torch.arange(10)
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
linespace = torch.linspace(3,10,steps=10)
linespace

tensor([ 3.0000,  3.7778,  4.5556,  5.3333,  6.1111,  6.8889,  7.6667,  8.4444,
         9.2222, 10.0000])

In [9]:
logspace = torch.logspace(start=-10, end=10, steps=10)
logspace

tensor([1.0000e-10, 1.6681e-08, 2.7826e-06, 4.6416e-04, 7.7426e-02, 1.2915e+01,
        2.1544e+03, 3.5938e+05, 5.9948e+07, 1.0000e+10])

In [10]:
eye = torch.eye(3)
eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
import numpy as np
import time
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [13]:
start = time.time()
zeros = torch.zeros(1,1)
end = time.time()

elapsed_time = end - start
print (f"{elapsed_time:.8f} seconds")

0.00000000 seconds


In [14]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = np.random.rand(100,100,100,100)
np_rand2 = np.random.rand(100,100,100,100)
start = time.time()

rand = (torch_rand1 @ torch_rand2)
end = time.time()

elapsed_time = end - start
print (f"{elapsed_time:.8f} seconds")
print (elapsed_time)

start = time.time()

rand = np.multiply(np_rand1, np_rand2)
end = time.time()

elapsed_time = end - start
print (f"{elapsed_time:.8f} seconds")
print (elapsed_time)

0.14224672 seconds
0.14224672317504883
0.26186371 seconds
0.26186370849609375


In [15]:
%%time
start = time.time()

zeros = torch.zeros(1,1)
end = time.time()

elapsed_time = end - start
print (f"{elapsed_time:.8f} seconds")

0.00000000 seconds
CPU times: total: 0 ns
Wall time: 997 μs


In [20]:
#torch.stack, torch.multinominal, torch.triu, input.T/input.transpose, nn.linear, torch.cat, f.softmax

#define a probability of tensor
probabilities = torch.tensor([0.1, 0.9])
#10% or 0.1 => 0
#90% or 0.9 => 1
#each probability pointst to the index of the probability in the tensor
#draw 5 samples from the multinominal distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print (samples)

tensor([1, 0, 1, 0, 1, 0, 1, 1, 1, 1])


In [23]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
#torch.cat concatenates tensors
out

tensor([1, 2, 3, 4, 5])

In [24]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [25]:
out = torch.triu(torch.ones(5,5))
#torch.triu returns the upper triangle
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [27]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [28]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [30]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [34]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])
stacked_tensor = torch.stack((tensor1, tensor2, tensor3), dim=0)
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,2, bias=False)
linear(sample)

tensor([-3.4784, -3.5088], grad_fn=<SqueezeBackward4>)

In [36]:
import torch.nn.functional as F
#create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

#apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])